### ISSUE TITLE
[CookieStore] Already Registered Command

### ISSUE THREAD

**Issue by Menteroth** [elijabesu/SauriCogs#16]
I'm curious if it would be possible to have this use something else other than `shop`?
Since this command is colliding with Redjumpman's shop cog.

**Comment by elijabesu** [comment]
Not really. If I wanted them to work simultaneously, I would have done it when first creating the cog. They do exactly the same thing and everyone using my cog is used to shop. If I were to rename it, it would have to have an alias "shop" exactly because of this which, again, would collide with Redjumpman's cog.

**Comment by Menteroth** [comment]
Yeah. That's okay. Just thought I would ask. And didn't know they did the same thing, hence my question in the first place. So all good I guess.

I unloaded RJ's shop cog to check out yours, but then I got this instead.
```
[2020-03-16 15:32:35] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "c:\__\coding\redenv\lib\site-packages\redbot\core\core_commands.py", line 115, in _load
    await bot.load_extension(spec)
  File "c:\__\coding\redenv\lib\site-packages\redbot\core\bot.py", line 903, in load_extension
    lib.setup(self)
  File "C:\__\coding\Soundwave\cogs\CogManager\cogs\cookiestore\__init__.py", line 5, in setup
    bot.add_cog(CookieStore(bot))
  File "c:\__\coding\redenv\lib\site-packages\redbot\core\bot.py", line 1036, in add_cog
    super().add_cog(cog)
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\bot.py", line 502, in add_cog
    cog = cog._inject(self)
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\cog.py", line 379, in _inject
    raise e
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\cog.py", line 374, in _inject
    bot.add_command(command)
  File "c:\__\coding\redenv\lib\site-packages\redbot\core\bot.py", line 1057, in add_command
    super().add_command(command)
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\core.py", line 1076, in add_command
    raise discord.ClientException('The alias {} is already an existing command or alias.'.format(alias))
discord.errors.ClientException: The alias backpack is already an existing command or alias.
```

**Comment by Menteroth** [comment]
You got anything about this? I know it's Adventure, because it worked when I unloaded it and tried your cookiestore cog. But Adventure is not something I can disable. So trying your shop (which I can do if this didn't occur, instead of using RJ's shop) right now won't even work.

**Comment by elijabesu** [comment]
Ooooh, yeah, my inventory command has `backpack` as an alias, I can remove that.

**Comment by Menteroth** [comment]
Great. Thanks.
