### ISSUE TITLE
[CookieStore] Command Error: inventory

### ISSUE THREAD

**Issue by Menteroth** [elijabesu/SauriCogs#17]
```
[2020-03-22 22:53:20] [ERROR] red: Exception in command 'inventory'
Traceback (most recent call last):
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\__\coding\Soundwave\cogs\CogManager\cogs\cookiestore\cookiestore.py", line 636, in inventory
    desc = humanize_list(lst)
  File "c:\__\coding\redenv\lib\site-packages\redbot\core\utils\chat_formatting.py", line 382, in humanize_list
    raise IndexError("Cannot humanize empty sequence") from None
IndexError: Cannot humanize empty sequence
```

**Comment by elijabesu** [comment]
Should be fixed, can you try it before I close it, please?

**Comment by Menteroth** [comment]
Yep. It works. Thanks.
