### ISSUE TITLE
[APPLICATION] Permission error + suggestion

### ISSUE THREAD

**Issue by Brandjuh** [elijabesu/SauriCogs#20]
Suggestion: Option to use roleid or role mention to give the role expect useing case intensive role name.

Error:
The bot does not give a warning when someone tries to give a person a role that is higher then the 
bot. 

```
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/application/application.py", line 217, in accept
    await target.add_roles(role_add)
  File "/root/redenv/lib/python3.8/site-packages/discord/member.py", line 641, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "/root/redenv/lib/python3.8/site-packages/discord/http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

![image](https://user-images.githubusercontent.com/26203955/80087884-0a07f300-855c-11ea-8a04-c607f56a5134.png)

**Comment by Brandjuh** [comment]
Also it looks like it needs admin perms instead of manage role and manage channels?

**Comment by elijabesu** [comment]
The user that does `[p]accept` has to have admin perms, yeah. 

The role check uses Red's `MessagePredicate.valid_role(ctx)` so it should take IDs, etc.

The error should be fixed tho.

**Comment by Brandjuh** [comment]
Tested it for a good 1.5 week and this error is gone :) Thanks
