### ISSUE TITLE
[Marriage] Cannot change action price

### ISSUE THREAD

**Issue by blanksuspect** [elijabesu/SauriCogs#21]
When attempting to change the price of an action with `[p]marriage changeprice [action] [price]`, the following error is thrown:

```py
Exception in command 'marriage changeprice'
Traceback (most recent call last):
  File "/home/blank/Desktop/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/blank/.local/share/Red-DiscordBot/cogs/CogManager/cogs/marriage/marriage.py", line 206, in marriage_changeprice
    await self.config.guild(ctx.guild).shit.get_raw(action)
  File "/home/blank/Desktop/red/lib/python3.8/site-packages/redbot/core/config.py", line 504, in get_raw
    raw = await self.driver.get(identifier_data)
  File "/home/blank/Desktop/red/lib/python3.8/site-packages/redbot/core/drivers/json.py", line 138, in get
    partial = partial[i]
KeyError: 'shit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/blank/Desktop/red/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/blank/Desktop/red/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/home/blank/Desktop/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/blank/Desktop/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/blank/Desktop/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'shit'
```

This happens only when supposedly valid parameters are passed, i.e. [p]marriage changeprice house 100000. Anything that would throw a valid exception, such as an incorrect action or a price < 0 returns the correct response.

**Comment by elijabesu** [comment]
Fixed with [93341ef](https://github.com/elijabesu/SauriCogs/commit/93341ef285f2c19e2ffe9d497c3bc7b178da66e1)
