### ISSUE TITLE
[Marriage] Error on price change

### ISSUE THREAD

**Issue by Brandjuh** [elijabesu/SauriCogs#23]
Hello Ellie, 

Marriage cog gives me some problems with the following commands:

**`!marriage changeprice fuck 10`** 
```
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/marriage/marriage.py", line 206, in marriage_changeprice
    await self.config.guild(ctx.guild).shit.get_raw(action)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 504, in get_raw
    raw = await self.driver.get(identifier_data)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/drivers/json.py", line 138, in get
    partial = partial[i]
KeyError: '443493512357347339'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: '443493512357347339'
```

**`pol.marriage changeprice flirt 100`**
```
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/marriage/marriage.py", line 206, in marriage_changeprice
    await self.config.guild(ctx.guild).shit.get_raw(action)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 504, in get_raw
    raw = await self.driver.get(identifier_data)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/drivers/json.py", line 138, in get
    partial = partial[i]
KeyError: '443493512357347339'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: '443493512357347339'
```
**`Pol.marriage changeprice flirt 100`**

```
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/marriage/marriage.py", line 206, in marriage_changeprice
    await self.config.guild(ctx.guild).shit.get_raw(action)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 504, in get_raw
    raw = await self.driver.get(identifier_data)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/drivers/json.py", line 138, in get
    partial = partial[i]
KeyError: 'shit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'shit'
```

**Comment by elijabesu** [comment]
Fixed with [93341ef](https://github.com/elijabesu/SauriCogs/commit/93341ef285f2c19e2ffe9d497c3bc7b178da66e1)
