### ISSUE TITLE
[Application error] TypeError: Object of type Role is not JSON serializable

### ISSUE THREAD

**Issue by Brandjuh** [elijabesu/SauriCogs#28]
```
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/application/application.py", line 217, in applysetup
    await self.config.guild(ctx.guild).applicant_id.set(applicant)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 257, in set
    await self.driver.set(self.identifier_data, value=value)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/drivers/json.py", line 146, in set
    value_copy = json.loads(json.dumps(value))
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Role is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Object of type Role is not JSON serializable
```

**Comment by Brandjuh** [comment]
```
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/application/application.py", line 48, in apply
    channel = get(ctx.guild.text_channels, id = await self.config.guild(ctx.guild).channel.id())
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 354, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'channel' is not a valid registered Group or value.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'channel' is not a valid registered Group or value.
```

**Comment by elijabesu** [comment]
Running setup again should fix it. But will add try and except.

**Comment by Brandjuh** [comment]
Still n ot working.

`Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/application/application.py", line 52, in apply
    channel = get(ctx.guild.text_channels, id = await self.config.guild(ctx.guild).channel.id())
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 354, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'channel' is not a valid registered Group or value.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'channel' is not a valid registered Group or value.`

**Comment by elijabesu** [comment]
Accidentally did `channel.id` instead of `channel_id`, my bad lol.

**Comment by Brandjuh** [comment]
Thanks for updating, however I get the following error in console 

```
[ERROR] red: Package loading failed
 Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 118, in _load
     await bot.load_extension(spec)
   File "/root/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 907, in load_extension
     lib = spec.loader.load_module()
   File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
   File "<frozen importlib._bootstrap_external>", line 962, in load_module
   File "<frozen importlib._bootstrap_external>", line 787, in load_module
   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
   File "<frozen importlib._bootstrap>", line 702, in _load
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/application/__init__.py", line 1, in <module>
     from .application import Application
   File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/application/application.py", line 45
     except TypeError, AttributeError:
                     ^
 SyntaxError: invalid syntax
```

**Comment by elijabesu** [comment]
oh ffs, update and it should work

**Comment by Brandjuh** [comment]
Updated, tested and it works! Thanks 😄
