### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by 1illeke** [elijabesu/SauriCogs#29]
When it asks what role can accept and deny, i mention the role but nothing happens afer

**Comment by 1illeke** [comment]
Got that to work, didn't know I had to use the role ids. But [p]apply doesn't work. just gives and error "Error in command 'apply'. Check your console or logs for details."

from console:
[2020-06-09 05:01:03] [ERROR] red: Exception in command 'apply'
Traceback (most recent call last):
  File "/home/lilleke/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/lilleke/.local/share/Red-DiscordBot/data/novi/cogs/CogManager/cogs/application/application.py", l
ine 52, in apply
    channel = get(ctx.guild.text_channels, id = await self.config.guild(ctx.guild).channel.id())
  File "/home/lilleke/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 354, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'channel' is not a valid registered Group or value.

**Comment by elijabesu** [comment]
Fixed. Accidentally did `channel.id` instead of `channel_id`, my bad lol.

With the role thingie, I cannot do anything about it because I am using Red's `MessagePredicate.valid_role(ctx)` which, according to their docs, should take `discord.Role` so not just its ID

**Comment by elijabesu** [comment]
NEVERMIND, their check really only accepts IDs... I'll try to make my own check but no promises cause finals in school this month.
