### ISSUE TITLE
Picking from no users in a role equals to IndexError: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by Skyridr** [elijabesu/SauriCogs#39]
When you attempt to rpick an empty role, it'll throw out an exception error:

```py
Traceback (most recent call last):
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/satan/satan/cogs/CogManager/cogs/pick/pick.py", line 54, in rpick
    winner = random.choice(role.members)
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: Cannot choose from an empty sequence```

**Comment by elijabesu** [comment]
Hihi, it should be fixed with the commit above. If there is any issue, lmk and I will reopen this issue.
