### ISSUE TITLE
Bug or Error on Cookies.py (steal cmd)

### ISSUE THREAD

**Issue by Hangenbo** [elijabesu/SauriCogs#50]
Here's the traceback... :/

_PS: The author have currently -4 cookies !_

```python

Exception in command 'cookies steal'
Traceback (most recent call last):
  File "/home/hangenbo/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/hangenbo/Striker/customcogs/cookies/cookies.py", line 124, in steal
    penalty = random.randint(1, cookies_penalty)
  File "/usr/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1, 0, -1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hangenbo/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/hangenbo/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/home/hangenbo/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1340, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/hangenbo/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/hangenbo/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: empty range for randrange() (1, 0, -1)```

**Comment by elijabesu** [comment]
It should be fixed with the commit linked above.

**Comment by Hangenbo** [comment]
Sorry for the delay, it works now ! 

Thanks for your work.
