### ISSUE TITLE
[Counting] Warn Message + Option

### ISSUE THREAD

**Issue by Menteroth** [elijabesu/SauriCogs#6]
The warn message won't work. Not getting a reply when wrong number is sent. It just deletes it. I set the timer to 5 seconds.

Also when people add a message after their count, for whatever reason they feel the need to do that, it will ignore the count. Maybe an option to be able to type a message after the count. If that works. So like an on/off or whatever.

https://ptb.discordapp.com/channels/240154543684321280/240212783503900673/651144708269015040

**Comment by Menteroth** [comment]
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\__\coding\Soundwave\cogs\CogManager\cogs\counting\counting.py", line 186, in on_message
    now = int(message.content)
ValueError: invalid literal for int() with base 10: '23174 Gran Turismo 1 Remastered for Nindeto Game Boy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\__\coding\venv\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "C:\__\coding\Soundwave\cogs\CogManager\cogs\counting\counting.py", line 235, in on_message
    f"The next message in this channel must be {next_number}"
UnboundLocalError: local variable 'next_number' referenced before assignment
Exception in thread Thread-14:
Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 554, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 521, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 586, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 556, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 457, in read
    n = self.readinto(b)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 491, in readinto
    return self._readinto_chunked(b)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 602, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(214 bytes read)
```

**Comment by elijabesu** [comment]
The warning worked but it didn't take into account when it was the same member - fixed with [commit dd9915ec0dde6283806b8985dc2f41e06914ddf6](https://github.com/elijabesu/SauriCogs/commit/dd9915ec0dde6283806b8985dc2f41e06914ddf6).

The feature is WIP, should be done within a few days.

**Comment by elijabesu** [comment]
The damn option is messing everything up and I honestly don't know how to fix it, ngl

**Comment by Menteroth** [comment]
No problem. Worth a shot hehe.
