### ISSUE TITLE
[Application] Getting error when trying to apply without role

### ISSUE THREAD

**Issue by Dragonias** [elijabesu/SauriCogs#62]
Hey there so after requesting the feature to make applications without roles I've finally worked on trying to set it up only to be met with this error right here:

Exception in command 'apply'
Traceback (most recent call last):
  File "/home/dragonias/.virtualenvs/demigra/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/dragonias/demigra/cogs/CogManager/cogs/application/application.py", line 78, in apply
    if not role_add:
UnboundLocalError: local variable 'role_add' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dragonias/.virtualenvs/demigra/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/dragonias/.virtualenvs/demigra/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/dragonias/.virtualenvs/demigra/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'role_add' referenced before assignment

But if you do the process with a role it works just fine.

**Comment by elijabesu** [comment]
Should be fixed with the update references above.
