### ISSUE TITLE
[Marriage] `[p]perform` and `[p]gift` error out for members that have spouses that are no longer in the server

### ISSUE THREAD

**Issue by jack1142** [elijabesu/SauriCogs#63]
```
[2021-04-24 03:54:38] [ERROR] red: Exception in command 'perform'
Traceback (most recent call last):
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/red-data/cogs/CogManager/cogs/marriage/marriage.py", line 885, in perform
    endtext = await self._maybe_divorce(ctx, spouse, endtext, contentment)
  File "/home/ubuntu/red-data/cogs/CogManager/cogs/marriage/marriage.py", line 1033, in _maybe_divorce
    s_temp = await m_conf(spouse).contentment()
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/redbot/core/config.py", line 1110, in member
    return self._get_base_group(self.MEMBER, str(member.guild.id), str(member.id))
AttributeError: 'NoneType' object has no attribute 'guild'
```
```
[2021-04-24 03:58:31] [ERROR] red: Exception in command 'gift'
Traceback (most recent call last):
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/red-data/cogs/CogManager/cogs/marriage/marriage.py", line 963, in gift
    endtext = await self._maybe_divorce(ctx, spouse, endtext, contentment)
  File "/home/ubuntu/red-data/cogs/CogManager/cogs/marriage/marriage.py", line 1033, in _maybe_divorce
    s_temp = await m_conf(spouse).contentment()
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/redbot/core/config.py", line 1110, in member
    return self._get_base_group(self.MEMBER, str(member.guild.id), str(member.id))
AttributeError: 'NoneType' object has no attribute 'guild'
```

It's possible that some other commands are affected as well but I have not looked more into it.

**Comment by elijabesu** [comment]
*Should* be fixed with the commit above. If not, reopen this, please
