### ISSUE TITLE
[CookieStore] Command raised an exception: KeyError

### ISSUE THREAD

**Issue by Notexe** [elijabesu/SauriCogs#75]
Hey,
I can't seem to add roles or items to the shop. I get these errors:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/var/lib/Red-DiscordBot/kai/cogs/CogManager/cogs/cookiestore/cookiestore.py", line 99, in cookiestoreset_add_role
    if await conf.roles.get_raw(role):
  File "/usr/lib/python3.9/site-packages/redbot/core/config.py", line 504, in get_raw
    raw = await self.driver.get(identifier_data)
  File "/usr/lib/python3.9/site-packages/redbot/core/drivers/json.py", line 138, in get
    partial = partial[i]
KeyError: 'roles'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'roles'
```
Trying to add an item changes the last line in the error with:
`Command raised an exception: KeyError: 'items'`

I'm running on the latest version of Red-DiscordBot (v3.4.13) with Python 3.9.

Thank you.

**Comment by elijabesu** [comment]
Hey, I'll look into/fix it on Saturday, thank you for reporting!

**Comment by elijabesu** [comment]
Fixed with the PR mentioned above
