### ISSUE TITLE
[BUG][Suggestion Cog] Old Suggestions cannot be Accepted/Rejected on Anonymous Mode 

### ISSUE THREAD

**Issue by Dragonias** [elijabesu/SauriCogs#94]
As written in the Title I recently tried to reject some old Suggestions we've had before swapping to the new Anonymous suggestion you've so wonderfully added for me, Thank you for that again but in doing so recieved this massive error when I tried to approve a old Suggestion

`Exception in command 'reject'
Traceback (most recent call last):
  File "/home/dragonias/.virtualenvs/demigra/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/dragonias/demigra/cogs/CogManager/cogs/suggestion/suggestion.py", line 170, in reject
    await self._finish_suggestion(ctx, suggestion_id, is_global, False, reason)
  File "/home/dragonias/demigra/cogs/CogManager/cogs/suggestion/suggestion.py", line 720, in _finish_suggestion
    footer = [f"Suggested in {suggested_in_guild.name} ({suggested_in_guild.id})", suggested_in_guild.icon_url]
AttributeError: 'NoneType' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dragonias/.virtualenvs/demigra/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/dragonias/.virtualenvs/demigra/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/dragonias/.virtualenvs/demigra/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'name'`

**Comment by elijabesu** [comment]
Y e a h, I expected that and still ignored it.

**Comment by elijabesu** [comment]
Should work now??

**Comment by Dragonias** [comment]
It does indeed! Thank you for your quick fix ♥
